# netlify.toml
[build]
  publish   = "public"
  functions = "netlify/functions"

# Compatibilidad con rutas antiguas /api/*
[[redirects]]
  from = "/api/tts"
  to   = "/.netlify/functions/tts"
  status = 200

[[redirects]]
  from = "/api/heygen-share"
  to   = "/.netlify/functions/heygen-embed"
  status = 200

# Fallback SPA (evita 404 en rutas internas)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
