[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/heygen-share"
  to = "/.netlify/functions/heygen-share"
  status = 200
  force = true
