[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.elevenlabs.io https://api.guestsvalencia.es https://*.heygen.com; img-src 'self' https: data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; frame-src https://console.heygen.com https://labs.heygen.com; media-src 'self' blob: data: https://api.elevenlabs.io;"
  Permissions-Policy = "microphone=*, camera=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
